/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderRouteImport } from './routes/leader'
import { Route as FollowerRouteImport } from './routes/follower'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'

const LeaderRoute = LeaderRouteImport.update({
  id: '/leader',
  path: '/leader',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowerRoute = FollowerRouteImport.update({
  id: '/follower',
  path: '/follower',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/follower': typeof FollowerRoute
  '/leader': typeof LeaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/follower': typeof FollowerRoute
  '/leader': typeof LeaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/follower': typeof FollowerRoute
  '/leader': typeof LeaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent' | '/follower' | '/leader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent' | '/follower' | '/leader'
  id: '__root__' | '/' | '/agent' | '/follower' | '/leader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  FollowerRoute: typeof FollowerRoute
  LeaderRoute: typeof LeaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leader': {
      id: '/leader'
      path: '/leader'
      fullPath: '/leader'
      preLoaderRoute: typeof LeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follower': {
      id: '/follower'
      path: '/follower'
      fullPath: '/follower'
      preLoaderRoute: typeof FollowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  FollowerRoute: FollowerRoute,
  LeaderRoute: LeaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
